// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMRVoIF1YuF4hqKFSgUWzcpiYM_a2a_WY',
    appId: '1:786040458798:web:09e61e27b221f0074d59bf',
    messagingSenderId: '786040458798',
    projectId: 'ocean-vessel',
    authDomain: 'ocean-vessel.firebaseapp.com',
    storageBucket: 'ocean-vessel.firebasestorage.app',
    measurementId: 'G-HLXG378W8F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1vDL86YFc5vuMNfSrjCA2PqfZzHWW3WY',
    appId: '1:786040458798:android:5af3672c8ced88734d59bf',
    messagingSenderId: '786040458798',
    projectId: 'ocean-vessel',
    storageBucket: 'ocean-vessel.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMaya-9Z18p8FCCSv1z3zfVIuwsG4YUko',
    appId: '1:786040458798:ios:63a6be82744906834d59bf',
    messagingSenderId: '786040458798',
    projectId: 'ocean-vessel',
    storageBucket: 'ocean-vessel.firebasestorage.app',
    iosBundleId: 'com.example.oceanVessel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMaya-9Z18p8FCCSv1z3zfVIuwsG4YUko',
    appId: '1:786040458798:ios:63a6be82744906834d59bf',
    messagingSenderId: '786040458798',
    projectId: 'ocean-vessel',
    storageBucket: 'ocean-vessel.firebasestorage.app',
    iosBundleId: 'com.example.oceanVessel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMRVoIF1YuF4hqKFSgUWzcpiYM_a2a_WY',
    appId: '1:786040458798:web:88adbeb540b277344d59bf',
    messagingSenderId: '786040458798',
    projectId: 'ocean-vessel',
    authDomain: 'ocean-vessel.firebaseapp.com',
    storageBucket: 'ocean-vessel.firebasestorage.app',
    measurementId: 'G-M35RBJ9SZ8',
  );
}
